<?php

return [
    "employee-referral" => [
        "title" => "New Employee Referral Form",
        "description" => "Employee Referral Form is used by employees to recommend potential candidates for open positions within a company.",
        "fields" => [
            "name" => [
                "label" => "Name",
                "type" => "text",
                "placeholder" => "Enter Full name",
                "required" => true,
            ],
            "referred_by" => [
                "label" => "Referred By",
                "type" => "text",
                "placeholder" => "Enter Full name",
                "required" => true,
            ],
            "employee_number" => [
                "label" => "Employee #",
                "type" => "number",
                "step" => 1,
                "min" => 1000,
                "max" => 9999,
                "required" => true,
                "placeholder" => "Enter Employee number",
                "rules" => ["min:1000", "max:9999"],
            ],
            "department" => [
                "label" => "Department",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter your Department",
            ],
            "supervisor" => [
                "label" => "Supervisor",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter Full name of Supervisor",
            ],
        ],
    ],
    "external-access-request" => [
        "title" => "External Access Request",
        "description" =>
        "To request an employee be granted external access to company information when outside of Elias Woodwork’s facilities please fill in the following and submit to HR for approval. If a mobile phone or laptop is required, please note that in the devices section. ",
        "fields" => [
            "supervisor" => [
                "label" => "Supervisor",
                "type" => "text",
                "placeholder" => "Enter Full name",
                "required" => true,
            ],
            "employee" => [
                "label" => "Employee",
                "type" => "text",
                "placeholder" => "Enter Full name",
                "required" => true,
            ],
            "access_type" => [
                "label" => "Type of Access (Check all that apply) ",
                "type" => "checkbox-group",
                "options" => ["External Email Access", "External VPN Access"],
                "required" => true,
            ],
            "device_used_email" => [
                "label" =>
                "Devices being used (MFA requires mobile phone): ",
                "type" => "text",
                "depends_on" => [
                    "field" => "access_type",
                    "disabled" => true,
                    "active_when" => "External Email Access",
                ],
                "placeholder" => "MFA requires mobile phone",
                "rules" => ["required_if:access_type, External Email Access", "max:255"],
            ],
            "device_used_vpn" => [
                "label" => "Devices being used: ",
                "type" => "text",
                "depends_on" => [
                    "field" => "access_type",
                    "disabled" => true,
                    "active_when" => "External VPN Access",
                ],
                "placeholder" => "MFA requires mobile phone",
                "rules" => ["required_if:access_type, External VPN Access", "max:255"],
            ],
            "date_range_start" => [
                "label" =>
                "Enter start date of approval ",
                "type" => "date",
                "rules" => ["required_without:permanent"],
            ],
            "date_range_end" => [
                "label" =>
                "Enter end date of approval ",
                "type" => "date",
                "depends_on" => [
                    "field" => "permanent",
                    "disabled" => false,
                    "disable_when" => true,
                ],
                "rules" => ["after_or_equal:date_range_start", "required_without:permanent"],
            ],
            "permanent" => [
                "label" => "
                ",
                "type" => "checkbox",
                "options" => "Permanent",
                "depends_on" => [
                    "field" => "date_range_end",
                    "disabled" => false,
                    "disable_when" => "filled",
                ],
            ],
            "reason" => [
                "label" =>
                "Reason (Provide a brief description of why this is needed)",
                "type" => "textarea",
                "required" => true,
            ],
        ],
    ],

    "job-transfer-request" => [
        "title" => "Job Transfer Request Form",
        "description" => "To submit a request to transfer to a different department or position within the company.",
        "fields" => [
            "date_of_completion" => [
                "label" => "Date",
                "type" => "date",
                "required" => true,
            ],
            "name" => [
                "label" => "Name",
                "type" => "text",
                "placeholder" => "Enter Full name",
                "required" => true,
            ],
            "employee_number" => [
                "label" => "Employee #",
                "type" => "number",
                "step" => 1,
                "min" => 1000,
                "max" => 9999,
                "required" => true,
                "placeholder" => "Enter Employee number ",
                "rules" => ["min:1000", "max:9999"],
            ],
            "department" => [
                "label" => "Department",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter your Department",
            ],
            "plant" => [
                "label" => "Plant",
                "type" => "select",
                "value" => [
                    ["value" => "Morden", "display" => "Morden"],
                    ["value" => "Winkler", "display" => "Winkler"]
                ],
                "required" => true,
            ],
            "shift" => [
                "label" => "Shift",
                "type" => "select",
                "value" => [
                    ["value" => "Morden Day", "display" => "Morden Day"],
                    ["value" => "Morden Evening", "display" => "Morden Evening"],
                    ["value" => "Office", "display" => "Office"],
                    ["value" => "Winkler Day", "display" => "Winkler Day"],
                    ["value" => "Winkler Evening", "display" => "Winkler Evening"],
                    ["value" =>   "Driver", "display" =>   "Driver"],
                    ["value" => "Cleaning", "display" => "Cleaning"],
                ],
                "required" => true,
            ],
            "seniority" => [
                "label" => "Seniority",
                "type" => "text",
                "placeholder" => "Enter total years of service",
            ],
            "position_requested" => [
                "label" => "Position requested",
                "type" => "text",
                "required" => true,
                "rules" => ["required", "max:255"],
                "placeholder" => "Enter your position requested",
            ],
            "requested_department" => [
                "label" => "Department",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter department name to transfer",
            ],
            "requested_plant" => [
                "label" => "Plant",
                "type" => "select",
                "value" => [
                    ["value" => "Morden", "display" => "Morden"],
                    ["value" => "Winkler", "display" => "Winkler"]
                ],
                "required" => true,
            ],
            "requested_shift" => [
                "label" => "Shift",
                "type" => "select",
                "value" => [
                    ["value" => "Morden Day", "display" => "Morden Day"],
                    ["value" => "Morden Evening", "display" => "Morden Evening"],
                    ["value" => "Office", "display" => "Office"],
                    ["value" => "Winkler Day", "display" => "Winkler Day"],
                    ["value" => "Winkler Evening", "display" => "Winkler Evening"],
                    ["value" =>   "Driver", "display" =>   "Driver"],
                    ["value" => "Cleaning", "display" => "Cleaning"],
                ],
                "required" => true,
            ],
            "schedule" => [
                "label" => "Choose type of time",
                "type" => "radio",
                "options" => ["Full Time", "Part Time"],
                "required" => true,
            ],
            "requested_date" => [
                "label" => "Requested Date of Transfer",
                "type" => "date",
                "required" => true,
            ],
            "reason_transferring" => [
                "label" => "Reason for transferring",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter reason for transfer",
            ],
            "experience" => [
                "label" => "Describe your work experience and how it relates to this position",
                "type" => "textarea",
                "rules" => ["max:22255"],
            ],
            "_hidden_fields" => [
                "application_received" => [
                    "label" => "application_received",
                    "value" => " ",
                ],
                "interview_date" => [
                    "label" => "interview_date",
                    "value" => " ",
                ],
                "to_be_int-viewed_by" => [
                    "label" => "to_be_int-viewed_by",
                    "value" => " "
                ],
                "comments" => [
                    "label" => "comments",
                    "value" => " "
                ],
                "action" => [
                    "label" => "action",
                    "value" => " "
                ],
                "HR_manager" => [
                    "label" => "HR_manager",
                    "value" => " "
                ],
                "date" => [
                    "label" => "date",
                    "value" => " "
                ],
            ],
        ],
    ],
    "bereavement-leave" => [
        "title" => "Bereavement Leave Form",
        "description" => "A Bereavement Leave Form is a document used by employees to formally request time off from work due to the death of a family member or close friend.",
        "fields" => [
            "date" => [
                "label" => "Date",
                "type" => "date",
                "required" => true,
            ],
            "employee_number" => [
                "label" => "Employee #",
                "type" => "number",
                "step" => 1,
                "min" => 1000,
                "max" => 9999,
                "required" => true,
                "placeholder" => "Enter Employee number ",
                "rules" => ["min:1000", "max:9999"],
            ],
            "name" => [
                "label" => "Name",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter your full name",
            ],
            "leave_type" => [
                "label" => "Subject: Bereavement Leave",
                "type" => "checkbox-group",
                "options" => ["Paid", "Unpaid up to three days"],
                "required" => true,
            ],
            "qty_days" => [
                "label" => "I am requesting bereavement leave for ",
                "type" => "number",
                "step" => 1,
                "min" => 1,
                "max" => 365,
                "required" => true,
                "placeholder" => "Enter the number of days ",
                "rules" => ["min:1", "max:365"],
            ],
            "date_range_start" => [
                "label" => "From ",
                "type" => "date",
                "required" => true,
            ],
            "date_range_end" => [
                "label" => "To ",
                "type" => "date",
                "rules" => ["after_or_equal:date_range_start"],
                "required" => true,
            ],
            "name_of_deceased" => [
                "label" => "Due to the death of ",
                "type" => "text",
                "required" => true,
                "placeholder" => "Name of deceased",
            ],
            "is_the_deceased_a" => [
                "label" => "Please choose one of the following",
                "type" => "checkbox-group",
                "options" => [
                    "Spouse",
                    "Child",
                    "Parent",
                    "Parent in law",
                    "Sibling or Grandchild",
                    "Sibling in law",
                    "Niece",
                    "Nephew or Grandparent",
                    "Uncle",
                    "Aunt or 1st Cousin",
                ],
                "required" => true,
            ],
            "notes-family" => [
                "label" => "Your consideration in this matter is appreciated",
                "type" => "notes",
                "value" => "Unpaid leave 3 day\'s for any family member",
            ],
            "notes-guide" => [
                "label" => "Paid Leave guidelines",
                "type" => "notes",
                "value" => "3 days - Spouse, child, Parent/in law, Sibling, or Grandchild
                1 day - Sibling in law, Niece, Nephew and Grandparent,
                1/2 day - Uncle, Aunt and 1st Cousin",
            ],
            "notes-ref" => [
                "label" => "",
                "type" => "notes",
                "value" => "For mor information please look up in the employee handbook pg. 60 or contact Human Resource Manager",
            ],
            "employee_initials" => [
                "label" => "Employee Initials",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter your initials example: A. B.",
                "rules" => ["required", "max:15"],
            ],
            "_hidden_fields" => [
                "approved_supervision_signature" => [
                    "label" => "approved_supervision_signature",
                    "value" => " ",
                ],
                "approved_human_resources" => [
                    "label" => "approved_human_resources",
                    "value" => " ",
                ],
            ],
        ],
    ],
    "staff-request" => [
        "title" => "Staffing Request Form",
        "description" => "A Staff Request Form is a form template designed to serve as a formalized process for department managers to communicate their staffing needs to human resources, recruitment teams, or relevant decision-makers within the organization.",
        "fields" => [
            "section_one" => [
                "label" => "",
                "value" => "Position Information",
                "type" => "notes",
            ],
            "type_of_position" => [
                "label" => "Type of position",
                "type" => "radio",
                "required" => true,
                "options" => ["New Position", "Replacement"],
            ],
            "date_of_request" => [
                "label" => "Date of Request",
                "type" => "date",
                "required" => true,
            ],
            "previous_employee" => [
                "label" => "Name of Previous Employee",
                "type" => "text",
                "rules" => ["required_if:type_of_position, Replacement"],
                "placeholder" => "Fill this field when choose replacement with a full name",
                "depends_on" => [
                    "field" => "type_of_position",
                    "disabled" => true,
                    "active_when" => "Replacement",
                ],
            ],
            "department" => [
                "label" => "Department",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter department",
            ],
            "shift" => [
                "label" => "Shift",
                "type" => "select",
                "value" => [
                    ["value" => "Day-shift", "display" => "Day-shift"],
                    ["value" => "Evening-shift", "display" => "Evening-shift"],
                    ["value" => "Night-shift", "display" => "Night-shift"],
                ],
                "required" => true,
            ],
            "supervisor" => [
                "label" => "Supervisor",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter Supervisor Name",
            ],
            "position_title" => [
                "label" => "Position title of new Candidate",
                "type" => "text",
                "required" => true,
                "placeholder" => "Enter position title for a new candidate",
            ],
            "required_start_date" => [
                "label" => "Required Start Date",
                "type" => "date",
                "required" => true,
            ],
            "required_end_date" => [
                "label" => "End Date(if Applicable)",
                "type" => "date",
                "rules" => ["after_or_equal:required_start_date"],
            ],
            "hourly_pay_range_from" => [
                "label" => "Pay range from ",
                "type" => "number",
                "step" => 0.01,
                "min" => 15.80,
                "required" => true,
                "placeholder" => "Minimum wage is $15.80 per hour effective October 1, 2024. ",
                "rules" => ["min:15.80", "max:999"],
            ],
            "hourly_pay_range_to" => [
                "label" => "Pay range to ",
                "type" => "number",
                "step" => 0.01,
                "min" => 15.80,
                "required" => true,
                "placeholder" => "Minimum wage is $15.80 per hour effective October 1, 2024. ",
                "rules" => ["min:15.80", "max:999"],
            ],
            "work_type" => [
                "label" => "Choose type of work",
                "type" => "radio",
                "required" => false,
                "options" => ["Permanent", "Temporary"],
                "required" => true,
            ],
            "schedule_type" => [
                "label" => "Choose type of time",
                "type" => "radio",
                "options" => ["Full Time", "Part Time"],
                "required" => true,
            ],
            "training_required_on_a_different_shift" => [
                "label" => "Training Required on a different shift",
                "type" => "radio",
                "options" => ["Yes", "No"],
                "required" => true,
            ],
            "training_shift" => [
                "label" => "Choose shift for training",
                "type" => "radio",
                "options" => [
                    "Day-shift",
                    "Evening-shift",
                    "Night-shift",
                    "Other – Please specify",
                ],
                "depends_on" => [
                    "field" => "training_required_on_a_different_shift",
                    "disabled" => true,
                    "active_when" => "Yes",
                ],
                "rules" => ["required_if:training_required_on_a_different_shift,Yes"],
            ],
            "other_shift_specify" => [
                "label" => "Other shift specify",
                "type" => "text",
                "placeholder" => "Specify shift",
                "depends_on" => [
                    "field" => "training_shift",
                    "disabled" => true,
                    "active_when" => "Other – Please specify",
                ],
            ],
            "rationale_for_staffing_request" => [
                "label" => "Rationale for Staffing Request",
                "type" => "textarea",
                "rules" => ["max:16350"],
            ],
            "section_competency" => [
                "label" => "",
                "value" => "Competency's needed for the job 0-10 ( please stay objective and as realistic as possible ) 0-not 5-needed10 -critical",
                "type" => "notes",
            ],
            "core_head" => [
                "label" => "",
                "value" => "Core",
                "type" => "notes",
            ],
            "woodworking_mech_skill" => [
                "label" => "Woodworking/Mech. skill",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "knowledge_of_product_or_machine" => [
                "label" => "Knowledge of Product/Machine",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "reliability_transportation" => [
                "label" => "Reliability/Transportation",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "drivers_license" => [
                "label" => "Drivers License",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "demonstrated_ability_to_learn" => [
                "label" => "Demonstrated ability to learn",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "understanding_of_good_leadership" => [
                "label" => "Understanding of good leadership",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "Reason_for_starting_here" => [
                "label" => "Reason for Starting here",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "Communication_and_interaction_with_others" => [
                "label" => "Communication and Interaction with Others",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "Member_1_Leader_10" => [
                "label" => "Member – 1 Leader - 10",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "goal_driven" => [
                "label" => "Goal Driven",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "motivation_for_the_job" => [
                "label" => "Motivation for the Job",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "career_oriented" => [
                "label" => "Career Oriented",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "good_self_assessment_honest" => [
                "label" => "Good self assessment, Honest",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "functional_head" => [
                "label" => "",
                "value" => "Functional/Job",
                "type" => "notes",
            ],
            "read_write_understand" => [
                "label" => "Read – Write - understand.",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "neatness_of_writing" => [
                "label" => "Neatness of writing",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "differentiating_of_colors" => [
                "label" => "Differentiating of Colors",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "math_skills" => [
                "label" => "Math Skills",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "problem_solving" => [
                "label" => "Problem Solving",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "exposure_to_dust_chemicals" => [
                "label" => "Exposure to Dust/Chemicals",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "measurements_mm_inch" => [
                "label" => "Measurements mm, inch",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "additional_head" => [
                "label" => "",
                "value" => "Additional",
                "type" => "notes",
            ],
            "physical_abilities" => [
                "label" => "Physical abilities",
                "type" => "number",
                "step" => 1,
                "min" => 0,
                "max" => 10,
                "placeholder" => " 0-not 5-needed 10 -critical",
                "rules" => ["min:0", "max:10"],
            ],
            "additional_abilities" => [
                "label" => "Please, specify any additional Competency you may need",
                "type" => "textarea",
                "rules" => ["max:1255"],
            ],
            "additional_KSAO" => [
                "label" => "Any additional KSAO (Knowledge, Skill, Ability and Other attribute)",
                "type" => "textarea",
                "rules" => ["max:1255"],
            ],
            "power_tool_training_required_during" => [
                "label" => "Power Tool Training required during",
                "type" => "checkbox-group",
                "options" => ["First week", "Second week", "Within 3 month"],
            ],
            "tools_first_week" => [
                "label" => "Tools for first week",
                "type" => "text",
                "depends_on" => [
                    "field" => "power_tool_training_required_during",
                    "disabled" => true,
                    "active_when" => "First week",
                ],
                "placeholder" => "Enter text",
            ],
            "tools_second_week" => [
                "label" => "Tools for second week",
                "type" => "text",
                "depends_on" => [
                    "field" => "power_tool_training_required_during",
                    "disabled" => true,
                    "active_when" => "Second week",
                ],
                "placeholder" => "Enter text",
            ],
            "tools_3_month" => [
                "label" => "Tools within 3 month",
                "type" => "text",
                "depends_on" => [
                    "field" => "power_tool_training_required_during",
                    "disabled" => true,
                    "active_when" => "Within 3 month",
                ],
                "placeholder" => "Enter text",
            ],
            "_hidden_fields" => [
                "supervisor_signature" => [
                    "label" => "supervisor_signature",
                    "value" => " ",
                ],
                "supervisor_signature_date" => [
                    "label" => "date",
                    "value" => " ",
                ],
                "production_manager_or_office_manager_signature" => [
                    "label" => "production_manager_or_office_manager_signature",
                    "value" => " ",
                ],
                "production_manager_or_office_manager_signature_date" => [
                    "label" => "date",
                    "value" => " ",
                ],
                "Executive_vice_president_human_resources" => [
                    "label" => "Executive_vice_president_human_resources",
                    "value" => " ",
                ],
                "Executive_vice_president_human_resources_date" => [
                    "label" => "date",
                    "value" => " ",
                ],
                "position_description_reviewed" => [
                    "label" => "position_description_reviewed",
                    "value" => " ",
                ],
                "Previous_job_posting_reviewed" => [
                    "label" => "Previous_job_posting_reviewed",
                    "value" => " ",
                ],
                "media_advertising_confirmed" => [
                    "label" => "media_advertising_confirmed",
                    "value" => " ",
                ],
                "web_page_updated" => [
                    "label" => "web_page_updated",
                    "value" => " ",
                ],
                "in_house_posting_updated" => [
                    "label" => "in_house_posting_updated",
                    "value" => " ",
                ],
                "date" => [
                    "label" => "date",
                    "value" => " ",
                ],
            ],
        ],
    ],
];
